version: '3'
volumes:
  data:
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: welcome
      MYSQL_DATABASE: timetracker
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: initialpassword
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
